# Generated by Django 2.1.2 on 2018-11-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('Fname', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Minit', models.CharField(blank=True, max_length=1)),
                ('Lname', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Grad_Year', models.CharField(max_length=4)),
                ('Job_Title', models.CharField(max_length=30)),
                ('Phone_Num', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=15)),
                ('Zipcode', models.CharField(max_length=5)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('Title', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Edate', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=15)),
                ('Zipcode', models.CharField(max_length=5)),
                ('Country', models.CharField(max_length=20)),
                ('Eattendants', models.ManyToManyField(to='testapp.Alumni')),
            ],
        ),
    ]
