# Generated by Django 2.1.2 on 2018-10-31 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20181030_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('AID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=15)),
                ('Minit', models.CharField(blank=True, max_length=1)),
                ('Lname', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Grad_Year', models.CharField(max_length=4)),
                ('Job_Title', models.CharField(max_length=30)),
                ('Phone_Num', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=15)),
                ('Zipcode', models.CharField(max_length=5)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('EID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('Edate', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=15)),
                ('State', models.CharField(max_length=15)),
                ('Zipcode', models.CharField(max_length=5)),
                ('Country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EvID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Events')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='firstname',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='hosts',
            name='UsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Users'),
        ),
        migrations.AddField(
            model_name='events',
            name='Eattendants',
            field=models.ManyToManyField(related_name='attendants', through='testapp.Attends', to='testapp.Users'),
        ),
        migrations.AddField(
            model_name='events',
            name='Ehosts',
            field=models.ManyToManyField(related_name='userhosts', through='testapp.Hosts', to='testapp.Users'),
        ),
        migrations.AddField(
            model_name='attends',
            name='EventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Events'),
        ),
        migrations.AddField(
            model_name='attends',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Users'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='are_alumni', to='testapp.Users'),
        ),
    ]
