# Generated by Django 2.1.2 on 2018-10-31 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20181031_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='AID',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='attends',
            name='EventID',
        ),
        migrations.RemoveField(
            model_name='attends',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='events',
            name='EID',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='EvID',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='UsID',
        ),
        migrations.AddField(
            model_name='attends',
            name='AlumFname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Alumni'),
        ),
        migrations.AddField(
            model_name='attends',
            name='EventTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Events'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='AlumFname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Alumni'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='EventTitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Events'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='Fname',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='Eattendants',
            field=models.ManyToManyField(related_name='attendants', through='testapp.Attends', to='testapp.Alumni'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Ehosts',
            field=models.ManyToManyField(related_name='userhosts', through='testapp.Hosts', to='testapp.Alumni'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Title',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
