# Generated by Django 2.1.2 on 2018-11-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20181031_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attends',
            name='AlumFname',
        ),
        migrations.RemoveField(
            model_name='attends',
            name='EventTitle',
        ),
        migrations.AlterField(
            model_name='events',
            name='Eattendants',
            field=models.ManyToManyField(to='testapp.Alumni'),
        ),
        migrations.DeleteModel(
            name='Attends',
        ),
    ]
