# Generated by Django 2.1.2 on 2018-11-01 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20181101_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Eattendants',
        ),
    ]
