# Generated by Django 2.1.2 on 2018-11-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_events_eattendants'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='Eattendants',
            field=models.ManyToManyField(to='testapp.Alumni'),
        ),
    ]
